---
# dump as passno provided as strings due to: https://github.com/ansible/ansible-modules-core/issues/1868
- name: Ensure mounts
  mount:
    dump: '{{ item.dump | default(0) | string }}'
    passno: '{{ item.passno | default(0) | string }}'
    fstype: nfs
    name: '{{ item.name }}'
    opts: '{{ item.opts | default(omit) }}'
    src: '{{ item.src }}'
    state: '{{ item.state | default("mounted") }}'
  with_items: nfs_client_mounts
