---
- include_vars: '{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml'
  tags:
  - nfs_client_install
  - nfs_client_config
  - nfs_client_service

- include: install.yml
  tags: nfs_client_install

- include: config.yml
  tags: nfs_client_config

- include: service.yml
  tags: nfs_client_service
