---
- name: Ensure service
  service:
    name: '{{ item }}'
    state: '{{ nfs_client_service_state }}'
    enabled: '{{ nfs_client_service_enabled }}'
  with_items: '{{ nfs_client_client_service_names }}'
